nohup python do_shallow_layer.py --task_name agnews --seed 42 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 44 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 45 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 42 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 43 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 45 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 46 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 43 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 44 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 46 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 42 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 44 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 45 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos last --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 42 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 43 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 45 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 46 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 43 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 44 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 46 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 42 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 44 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 45 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 42 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 43 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 45 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 46 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos first --sample_size 1000 --demonstration_shot 1 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 43 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 44 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 46 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 42 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 44 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 45 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 42 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 43 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 45 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 46 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 43 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 44 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 46 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos last --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 42 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 44 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 45 --model_name gpt-j-6b --mask_layer_num 5 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 42 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 43 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 45 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 46 --model_name gpt-j-6b --mask_layer_num 1 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 43 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 44 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 46 --model_name gpt-j-6b --mask_layer_num 3 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 42 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name emo --seed 44 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
nohup python do_shallow_layer.py --task_name agnews --seed 45 --model_name gpt-j-6b --mask_layer_num 7 --mask_layer_pos first --sample_size 1000 --demonstration_shot 2 --device cuda:2
